[package]
name = "lightmatrix"
version = "0.1.0"
authors = ["Bill Liu"]
description = "lightweight 2D matrix utilities"
documentation = "https://docs.rs/lightmatrix"
homepage = "https://github.com/exbibyte/lightmatrix"
keywords = ["matrix"]
edition = "2018"

[dependencies]
num-traits = "0.2"